version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - tech-test-network

  backend:
    build:
      context: ./backend
    container_name: backend_tech_test
    command: yarn dev
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8181:8181"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: app_db
      DB_PORT: 3306
      PORT: 8181
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tech-test-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_tech_test
    command: yarn dev
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tech-test-network

volumes:
  mysql_data:

networks:
  tech-test-network:
    driver: bridge
